const fs = require('fs');
const path = require('path');

const iconsDir = path.join(__dirname, '..', 'frontend', 'public', 'icons');
if (!fs.existsSync(iconsDir)) {
  fs.mkdirSync(iconsDir, { recursive: true });
}

// 192x192 base64 PNG (solid teal square with a white letter E)
const icon192Base64 = 'iVBORw0KGgoAAAANSUhEUgAAAMAAAADACAMAAABlTdndAAAAG1BMVEUAAABNeKZNdKZNdKZNdKZNdKZNdKZNdKZNdKZ/123LAAAACXRefSAAAAAQAAAAEAAAQAAAAEAAAO5z+4gAAAAnRSTlMAGCBAQGBwgHCAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIDw8H+rAAAAt0lEQVR42u3BMQEAAADCoPVPbQ0PoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA4M3AAAABm03tAAAAAElFTkSuQmCC';

// 512x512 base64 PNG
const icon512Base64 = 'iVBORw0KGgoAAAANSUhEUgAAAgAAAAIACAMAAADD3C76AAAAG1BMVEUAAABNeKZNdKZNdKZNdKZNdKZNdKZNdKZNdKZ/123LAAAACXRefSAAAAAQAAAAEAAAQAAAAEAAAO5z+4gAAAAnRSTlMAGCBAQGBwgHCAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIDw8H+rAAAAt0lEQVR42u3BMQEAAADCoPVPbQ0PoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA4M3AAAABm03tAAAAAElFTkSuQmCC';

fs.writeFileSync(path.join(iconsDir, 'icon-192.png'), Buffer.from(icon192Base64, 'base64'));
fs.writeFileSync(path.join(iconsDir, 'icon-512.png'), Buffer.from(icon512Base64, 'base64'));

console.log('Icons generated successfully.');
